GET http://localhost:3000/api/contact

### Enviar formulario (cambiar los valores según sea necesario)
POST http://localhost:3000/api/contact/submit
Content-Type: application/json

{
  "name": "Frank GP",
  "email": "fgp555@gmail.com",
  "subject": "Gracias por contactarnos",
  "message": "Me gustaría obtener más información. (request.http file)",
  "currentUrl": "http://example.com/contact"
}

